FROM node:10.24.1-buster
RUN wget https://github.com/opensearch-project/OpenSearch-Dashboards/archive/refs/tags/2.0.0.tar.gz \
		&& apt update && apt install -y ca-certificates curl gnupg lsb-release \
		&& tar -xzvf 2.0.0.tar.gz \
		&&  curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
	&& echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
		&& apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

WORKDIR /Opensearch-dashboard-2.0.0
	
